apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- csi/application.yaml
- external-secrets/application.yaml
- reloader/application.yaml
- ../../kyverno-policies/application.yaml
- kyverno/application.yaml

