apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
          - list:
              elements:
                - name: ingress
                  namespace: ingress-nginx
                  chart: ingress-nginx
                  repo: https://kubernetes.github.io/ingress-nginx
                  version: 4.12.0
          - git:
              repoURL: 'https://github.com/pc-dae/observability-hub-poc.git'
              revision: main
              files:
                - path: local-cluster/config/cluster-params.yaml
  template:
    metadata:
      name: {{.name}}
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: {{.repo}}
        chart: {{.chart}}
        targetRevision: {{.version}}
        helm:
          values: |
            controller:
              service:
                annotations:
                  external-dns.alpha.kubernetes.io/hostname: {{.dnsSuffix}}
              ingressClassResource:
                default: "true"
              watchIngressWithoutClass: "true"
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: {{.namespace}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
