apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: local-ca-issuer
  annotations:
    cert-manager.io/inject-ca-from: cert-manager/ca-key-pair
spec:
  ca:
    secretName: ca-key-pair
