apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: mimir-distributed
    helm:
      values: |
        mimir:
          structuredConfig:
            memberlist:
              join_members:
                - '{{ printf "%s-gossip-ring.%s.svc.cluster.local" (include "mimir.fullname" .) .Release.Namespace }}'
            alertmanager:
              data_dir: /data/alertmanager
            ruler:
              alertmanager_url: http://localhost:8080/alertmanager
            query_scheduler:
              max_outstanding_per_tenant: 2048
        querier:
          replicas: 2
        alertmanager:
          enabled: true
        rollout_operator:
          enabled: false
        nginx:
          enabled: true
        compactor:
          command:
            - /bin/sh
            - -c
            - |
              set -ex
              until nslookup mimir-gossip-ring.monitoring.svc.cluster.local; do
                echo "Waiting for memberlist DNS to be available..."
                sleep 3
              done
              echo "Starting mimir compactor with args: $@"
              /bin/mimir "$@"
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
