apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: mimir-distributed
    targetRevision: 5.1.0
    helm:
      values: |
        mimir:
          structuredConfig:
            memberlist:
              join_members:
                - '{{ printf "%s-gossip-ring.%s.svc.cluster.local" (include "mimir.fullname" .) .Release.Namespace }}'
            alertmanager:
              data_dir: /data/alertmanager
            ruler:
              alertmanager_url: http://localhost:8080/alertmanager
        alertmanager:
          enabled: true
        rollout_operator:
          enabled: false
        nginx:
          enabled: true
        compactor:
          extraArgs:
            - "--config.file=/etc/mimir/mimir.yaml"
          command:
            - /bin/sh
            - -ec
            - |
              until nslookup $(MIMIR_MEMBERLIST_JOIN_MEMBERS); do
                echo "Waiting for memberlist DNS to be available..."
                sleep 3
              done
              /bin/mimir --target=compactor $(EXTRA_ARGS)
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
