dnsSuffix: kubernetes.docker.internal
clusterIP: TBA
storageClass: hostpath
namespaces:
 - vault
 - ingress-nginx
 - monitoring
 - kafka
 - argocd
 - grafana
 - otel-collector
 - cert-manager
caCert: |
  