apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager/application.yaml
- csi/application.yaml
- external-secrets/application.yaml
- reloader/application.yaml
- nginx/namespace.yaml
- vault/namespace.yaml
- ../cert-config
